# Generated by rust2rpm 27
%bcond check 1
%global debug_package %{nil}

%global crate jsonschema

Name:           rust-jsonschema
Version:        0.37.1
Release:        %autorelease
Summary:        JSON schema validaton library

License:        MIT
URL:            https://crates.io/crates/jsonschema
Source:         %{crates_source}
# Automatically generated patch to strip dependencies and normalize metadata
Patch:          jsonschema-fix-metadata-auto.diff

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
JSON schema validaton library.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+arbitrary-precision-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+arbitrary-precision-devel %{_description}

This package contains library source intended for building other packages which
use the "arbitrary-precision" feature of the "%{crate}" crate.

%files       -n %{name}+arbitrary-precision-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+reqwest-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+reqwest-devel %{_description}

This package contains library source intended for building other packages which
use the "reqwest" feature of the "%{crate}" crate.

%files       -n %{name}+reqwest-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+resolve-async-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+resolve-async-devel %{_description}

This package contains library source intended for building other packages which
use the "resolve-async" feature of the "%{crate}" crate.

%files       -n %{name}+resolve-async-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+resolve-file-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+resolve-file-devel %{_description}

This package contains library source intended for building other packages which
use the "resolve-file" feature of the "%{crate}" crate.

%files       -n %{name}+resolve-file-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+resolve-http-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+resolve-http-devel %{_description}

This package contains library source intended for building other packages which
use the "resolve-http" feature of the "%{crate}" crate.

%files       -n %{name}+resolve-http-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
